// Generated by gencpp from file main_controller/ControllerData.msg
// DO NOT EDIT!


#ifndef MAIN_CONTROLLER_MESSAGE_CONTROLLERDATA_H
#define MAIN_CONTROLLER_MESSAGE_CONTROLLERDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace main_controller
{
template <class ContainerAllocator>
struct ControllerData_
{
  typedef ControllerData_<ContainerAllocator> Type;

  ControllerData_()
    : StatusControl(0)
    , data()  {
    }
  ControllerData_(const ContainerAllocator& _alloc)
    : StatusControl(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef int16_t _StatusControl_type;
  _StatusControl_type StatusControl;

   typedef std::vector<int16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int16_t>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::main_controller::ControllerData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::main_controller::ControllerData_<ContainerAllocator> const> ConstPtr;

}; // struct ControllerData_

typedef ::main_controller::ControllerData_<std::allocator<void> > ControllerData;

typedef boost::shared_ptr< ::main_controller::ControllerData > ControllerDataPtr;
typedef boost::shared_ptr< ::main_controller::ControllerData const> ControllerDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::main_controller::ControllerData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::main_controller::ControllerData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::main_controller::ControllerData_<ContainerAllocator1> & lhs, const ::main_controller::ControllerData_<ContainerAllocator2> & rhs)
{
  return lhs.StatusControl == rhs.StatusControl &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::main_controller::ControllerData_<ContainerAllocator1> & lhs, const ::main_controller::ControllerData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace main_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::main_controller::ControllerData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::main_controller::ControllerData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::main_controller::ControllerData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::main_controller::ControllerData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::main_controller::ControllerData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::main_controller::ControllerData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::main_controller::ControllerData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "244e1cda6d3e37f787f007f1bc662fea";
  }

  static const char* value(const ::main_controller::ControllerData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x244e1cda6d3e37f7ULL;
  static const uint64_t static_value2 = 0x87f007f1bc662feaULL;
};

template<class ContainerAllocator>
struct DataType< ::main_controller::ControllerData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "main_controller/ControllerData";
  }

  static const char* value(const ::main_controller::ControllerData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::main_controller::ControllerData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 StatusControl\n"
"int16[] data\n"
;
  }

  static const char* value(const ::main_controller::ControllerData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::main_controller::ControllerData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.StatusControl);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControllerData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::main_controller::ControllerData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::main_controller::ControllerData_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "StatusControl: ";
    Printer<int16_t>::stream(s, indent + "  ", v.StatusControl);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "data: ";
    if (v.data.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<int16_t>::stream(s, true ? std::string() : indent + "    ", v.data[i]);
    }
    if (v.data.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAIN_CONTROLLER_MESSAGE_CONTROLLERDATA_H
