// Generated by gencpp from file tuw_geometry_msgs/TwistWithOrientation.msg
// DO NOT EDIT!


#ifndef TUW_GEOMETRY_MSGS_MESSAGE_TWISTWITHORIENTATION_H
#define TUW_GEOMETRY_MSGS_MESSAGE_TWISTWITHORIENTATION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Twist.h>

namespace tuw_geometry_msgs
{
template <class ContainerAllocator>
struct TwistWithOrientation_
{
  typedef TwistWithOrientation_<ContainerAllocator> Type;

  TwistWithOrientation_()
    : header()
    , twist()
    , orientation(0.0)  {
    }
  TwistWithOrientation_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , twist(_alloc)
    , orientation(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _twist_type;
  _twist_type twist;

   typedef double _orientation_type;
  _orientation_type orientation;





  typedef boost::shared_ptr< ::tuw_geometry_msgs::TwistWithOrientation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tuw_geometry_msgs::TwistWithOrientation_<ContainerAllocator> const> ConstPtr;

}; // struct TwistWithOrientation_

typedef ::tuw_geometry_msgs::TwistWithOrientation_<std::allocator<void> > TwistWithOrientation;

typedef boost::shared_ptr< ::tuw_geometry_msgs::TwistWithOrientation > TwistWithOrientationPtr;
typedef boost::shared_ptr< ::tuw_geometry_msgs::TwistWithOrientation const> TwistWithOrientationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tuw_geometry_msgs::TwistWithOrientation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tuw_geometry_msgs::TwistWithOrientation_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tuw_geometry_msgs::TwistWithOrientation_<ContainerAllocator1> & lhs, const ::tuw_geometry_msgs::TwistWithOrientation_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.twist == rhs.twist &&
    lhs.orientation == rhs.orientation;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tuw_geometry_msgs::TwistWithOrientation_<ContainerAllocator1> & lhs, const ::tuw_geometry_msgs::TwistWithOrientation_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tuw_geometry_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tuw_geometry_msgs::TwistWithOrientation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tuw_geometry_msgs::TwistWithOrientation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tuw_geometry_msgs::TwistWithOrientation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tuw_geometry_msgs::TwistWithOrientation_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tuw_geometry_msgs::TwistWithOrientation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tuw_geometry_msgs::TwistWithOrientation_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tuw_geometry_msgs::TwistWithOrientation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ad8e7cc3b8974787cc18131989636e17";
  }

  static const char* value(const ::tuw_geometry_msgs::TwistWithOrientation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xad8e7cc3b8974787ULL;
  static const uint64_t static_value2 = 0xcc18131989636e17ULL;
};

template<class ContainerAllocator>
struct DataType< ::tuw_geometry_msgs::TwistWithOrientation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tuw_geometry_msgs/TwistWithOrientation";
  }

  static const char* value(const ::tuw_geometry_msgs::TwistWithOrientation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tuw_geometry_msgs::TwistWithOrientation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"geometry_msgs/Twist twist\n"
"float64 orientation\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3 linear\n"
"Vector3 angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::tuw_geometry_msgs::TwistWithOrientation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tuw_geometry_msgs::TwistWithOrientation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.twist);
      stream.next(m.orientation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TwistWithOrientation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tuw_geometry_msgs::TwistWithOrientation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tuw_geometry_msgs::TwistWithOrientation_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "twist: ";
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.twist);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "orientation: ";
    Printer<double>::stream(s, indent + "  ", v.orientation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUW_GEOMETRY_MSGS_MESSAGE_TWISTWITHORIENTATION_H
